# Generated by Django 3.2.6 on 2021-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210803_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='user',
        ),
        migrations.AddField(
            model_name='management',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
